version: '3.4'
services:
  client:
    # Dev
    # build: '../nebula-go-api/'
    # Prod
    image: niania/nebula-http-client:0.0.1
    environment:
      USER: root
    ports:
      - 8080:8080
    networks: 
      - nebula-web
  web:
    # Dev
    # build: '../.'
    # Prod
    image: niania/nebula-web-console:0.0.6
    environment:
      USER: root
      WORKING_DIR: ${WORKING_DIR}
    ports:
      - 7001:7001
    depends_on:
      - client
    volumes:
      - ${WORKING_DIR}:${WORKING_DIR}:rw
    networks: 
      - nebula-web
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nebula.conf
    depends_on:
      - client
      - web
    networks: 
      - nebula-web
    ports:
      - 80:80
  importer:
    image: vesoft/nebula-importer:latest
    networks:
      - nebula-web
    ports:
      - 5699:5699
    command: nebula-importer --port 5699 --callback http://nginx:80/api/import/callback

networks: 
  nebula-web:
